services:
  app:
    build:
        context: .
        dockerfile: Dockerfile.local
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      - APP_URL=${APP_URL_LOCAL}
    networks:
      - e-museu_network
    depends_on:
      - db

  web: 
    image: nginx:stable-alpine3.20-perl
    ports:
      - "${WEB_SERVER_PORT_LOCAL}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - e-museu_network 
    depends_on:
      - app

  db:
    image: mysql:8.0-debian
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - e-museu_network 

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: marketcore-api-pgweb
    restart: always
    ports:
      - "8011:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
    depends_on:
      - db
    networks:
      - e-museu_network

networks:
  e-museu_network:
    driver: bridge